WIFI_SSID: ""
WIFI_PASSWORD: ""
OTA_PASSWORD: "asdf1234"
ENABLE_WEATHER_API: "false"
WEATHER_KEY: "" # Sign up at https://openweathermap.org/ to get an API key
WEATHER_CITY_ID: "2158177" # Australia/Melbourne
UNITS: metric
LANG: en
TIME_ZONE: Australia/Melbourne
SNTP_SERVER_1: "0.pool.ntp.org"
SNTP_SERVER_2: "1.pool.ntp.org"
SNTP_SERVER_3: "2.pool.ntp.org"
LATITUDE: "-37.9518" # Australia/Melbourne
LONGITUDE: "145.3189"
QR_WEBSITE_URL: "https://multipolygon.net"
QR_RSS_URL: "https://multipolygon.net/rss.xml"
QR_VCARD: |-
  BEGIN:VCARD
  VERSION:3.0
  N:Lastname;Firstname;;;
  EMAIL:email@multipolygon.net
  URL:https://multipolygon.net
  SOURCE:https://multipolygon.net/me.vcf
  REV:2407
  END:VCARD
BIRTHDAY: "0"
BIRTHMONTH: "0"
BIRTHDAY1: "0"
BIRTHMONTH1: "0"
BIRTHDAY2: "0"
BIRTHMONTH2: "0"
HOME_ASSISTANT_API_KEY: "your-random-key-here" # https://esphome.io/components/api.html
